export const SITE_CONFIG = {
  bookingUrl: "",
};

export const DEMO_SITES = [
  {
    id: "group",
    name: "All sites",
    revenue: 48520,
    forecast: 47240,
    labourCost: 11980,
    grossProfit: 34210,
    stockAlerts: 7,
    approvals: 5,
    orders: 1384,
  },
  {
    id: "leeds",
    name: "Leeds",
    revenue: 17840,
    forecast: 17120,
    labourCost: 4380,
    grossProfit: 12630,
    stockAlerts: 2,
    approvals: 2,
    orders: 514,
  },
  {
    id: "manchester",
    name: "Manchester",
    revenue: 16460,
    forecast: 15980,
    labourCost: 4120,
    grossProfit: 11640,
    stockAlerts: 4,
    approvals: 1,
    orders: 467,
  },
  {
    id: "glasgow",
    name: "Glasgow",
    revenue: 14220,
    forecast: 14140,
    labourCost: 3480,
    grossProfit: 9940,
    stockAlerts: 1,
    approvals: 2,
    orders: 403,
  },
];

export const REVENUE_CURVES = {
  group: [38, 46, 43, 58, 64, 61, 78, 72, 84, 88, 81, 94],
  leeds: [32, 39, 37, 52, 58, 55, 71, 67, 75, 82, 77, 89],
  manchester: [42, 48, 45, 61, 68, 64, 76, 73, 87, 85, 83, 91],
  glasgow: [35, 41, 44, 49, 57, 58, 69, 71, 78, 84, 79, 88],
};

export const ROTA_SHIFTS = [
  { role: "Kitchen", name: "Maya K.", start: 8, end: 16, tone: "strong" },
  { role: "Kitchen", name: "Callum R.", start: 11, end: 20, tone: "soft" },
  { role: "Floor", name: "Imani T.", start: 10, end: 18, tone: "strong" },
  { role: "Floor", name: "Theo W.", start: 12, end: 21, tone: "soft" },
  { role: "Manager", name: "Nadia P.", start: 9, end: 18, tone: "neutral" },
];

export const PNL_ROWS = [
  { key: "netSales", actual: 48520, budget: 47240 },
  { key: "cogs", actual: -14310, budget: -13940 },
  { key: "grossProfit", actual: 34210, budget: 33300 },
  { key: "labour", actual: -11980, budget: -11620 },
  { key: "operatingContribution", actual: 22230, budget: 21680 },
];

export const CONTENT_CALENDAR = [
  { day: "12", channel: "Google", status: "approved" },
  { day: "15", channel: "Website", status: "draft" },
  { day: "18", channel: "Email", status: "review" },
  { day: "22", channel: "Instagram", status: "planned" },
];

export const MODULES = [
  { id: "forecast", size: "wide" },
  { id: "workforce", size: "standard" },
  { id: "inventory", size: "tall" },
  { id: "finance", size: "standard" },
  { id: "crm", size: "standard" },
  { id: "marketing", size: "wide" },
];

export const LOOP_STEPS = ["forecast", "rota", "inventory", "reconcile", "report"];

export const FAQ_KEYS = ["concept", "pos", "approval", "accounting", "pilot"];

export const TEXT = {
  en: {
    pageTitle: "RNG | Restaurant operations, connected",
    pageDescription: "An interactive concept for one restaurant operating system across forecasting, labour, stock, finance, CRM and marketing.",
    skip: "Skip to main content",
    concept: "Interactive product concept",
    sample: "Sample data",
    nav: [
      ["Product", "#product"],
      ["Forecast", "#forecast"],
      ["Workforce", "#workforce"],
      ["Reports", "#reports"],
      ["Marketing", "#marketing"],
    ],
    explore: "Explore the demo",
    book: "Book a demo",
    language: "繁中",
    hero: {
      title: "Run every site from one operating system.",
      body: "Connect sales, labour, stock, finance and marketing before small variances become expensive problems.",
      imageAlt: "Restaurant manager reviewing operations on a tablet beside an open kitchen",
    },
    workspace: {
      title: "Today at a glance",
      selector: "Workspace location",
      revenue: "Net revenue",
      forecast: "Forecast",
      labour: "Labour cost",
      gp: "Gross profit",
      alerts: "Stock alerts",
      approvals: "Approvals",
      live: "Updated from one shared model",
      varianceAhead: "ahead of forecast",
      belowForecast: "below forecast",
      orders: "orders today",
    },
    loop: {
      title: "One forecast runs the whole week.",
      body: "Every decision starts from the same version of demand, so operations and finance stop arguing over whose number is right.",
      labels: {
        forecast: "Forecast demand",
        rota: "Build rotas",
        inventory: "Order inventory",
        reconcile: "Reconcile accounts",
        report: "Publish the report",
      },
      details: {
        forecast: ["Demand is versioned", "Revenue and item demand update together."],
        rota: ["Coverage meets demand", "Recommended hours stay inside the labour budget."],
        inventory: ["Stock follows demand", "Suggested orders account for recipe usage and waste."],
        reconcile: ["Exceptions come first", "Sales, settlements and bank deposits line up before close."],
        report: ["One approved view", "Monthly reporting keeps every source and variance traceable."],
      },
    },
    platform: {
      title: "The operating system behind every shift.",
      body: "Move from a live issue to the decision, owner and financial impact without changing tools.",
      items: {
        forecast: ["Forecast and variance", "Five-week demand planning with actual, budget and forecast views."],
        workforce: ["Workforce", "Build, approve and publish labour plans against demand."],
        inventory: ["Inventory", "Recipes, purchase orders, counts, waste and theoretical COGS."],
        finance: ["Finance", "Double-entry workflows, settlement matching and month-end control."],
        crm: ["Guest and B2B CRM", "Separate guest insight from commercial pipelines and projects."],
        marketing: ["Marketing and CMS", "Plan content, manage approval and report on discoverability."],
      },
      open: "Open module",
    },
    simulator: {
      title: "Test the week before it happens.",
      body: "Adjust a few operating assumptions and see how the same scenario changes revenue, labour and stock planning.",
      period: "Forecast period",
      periods: ["Next 7 days", "Next 14 days", "Next 5 weeks"],
      promotion: "Promotion",
      promotions: { none: "None", standard: "Lunch offer", major: "Major launch" },
      weather: "Weather",
      weatherOptions: { dry: "Dry", rain: "Rain", hot: "Hot" },
      footfall: "Expected footfall",
      projectedRevenue: "Projected revenue",
      labourHours: "Recommended hours",
      stockUnits: "Stock units",
      variance: "Variance to baseline",
      caveat: "Demonstration model only. It does not represent a live forecast or guaranteed outcome.",
    },
    rota: {
      title: "A rota the manager can explain.",
      body: "Recommendations show coverage and cost first. Nothing is published until the right person approves it.",
      statuses: { proposed: "Proposed", approved: "Approved", published: "Published" },
      demand: "Demand coverage",
      budget: "Labour budget",
      scheduled: "Scheduled",
      people: "Team schedule",
      stateCopy: {
        proposed: "AI recommendation is ready for manager review.",
        approved: "Manager approved the plan. It is not visible to staff yet.",
        published: "The approved rota is now visible to the team.",
      },
    },
    reports: {
      title: "Month-end without the spreadsheet chase.",
      body: "Review finance, operations and growth from the same locked sample snapshot.",
      tabs: { pnl: "P&L", operations: "Operations", growth: "Growth" },
      preview: "Preview report",
      month: "June management report",
      actual: "Actual",
      budget: "Budget",
      variance: "Variance",
      labels: {
        netSales: "Net sales",
        cogs: "Cost of goods",
        grossProfit: "Gross profit",
        labour: "Labour",
        operatingContribution: "Operating contribution",
      },
      operations: [
        ["Order accuracy", "96.4%", "Stable across all sites"],
        ["Waste to sales", "1.8%", "Leeds improved after recipe review"],
        ["Labour to sales", "24.7%", "0.5 points above plan"],
      ],
      growth: [
        ["Returning guests", "41.2%", "Up from the prior sample period"],
        ["Organic discovery", "+8.6%", "Local pages drove the change"],
        ["Campaign revenue", "£6,840", "Tracked through campaign links"],
      ],
      explanation: "Revenue finished ahead of plan, while labour pressure came from longer Friday closing shifts. Review close-down coverage before changing the sales plan.",
    },
    marketing: {
      title: "Campaign, content and discoverability in one view.",
      body: "Turn operational context into an approved campaign, a local landing page and one monthly performance story.",
      campaign: "Summer weekday lunch",
      objective: "Increase Monday to Thursday lunch visits",
      budget: "Sample budget",
      audience: "Local guests, 2+ visits",
      calendar: "Content calendar",
      website: "Landing page preview",
      desktop: "Desktop",
      mobile: "Mobile",
      previewTitle: "Lunch that fits the working day.",
      previewBody: "A focused weekday menu, ready when the lunch break starts.",
      previewCta: "View the menu",
      checklist: "SEO, GEO and AEO readiness",
      checks: ["Restaurant schema", "Local entity facts", "Clear answer summary", "Source and review date"],
      statuses: { approved: "Approved", draft: "Draft", review: "In review", planned: "Planned" },
    },
    roles: {
      title: "Head office clarity. Floor-level usefulness.",
      body: "The same operating model changes shape for the people making decisions and the people running service.",
      items: ["Head office", "Finance", "Site managers", "Team members"],
      imageAltOne: "Restaurant counter with timber service line and green ceiling",
      imageAltTwo: "Independent restaurant frontage with a glazed entrance",
    },
    faq: {
      title: "Questions before the demo.",
      items: {
        concept: ["Is this the finished product?", "No. This website is an interactive product concept using local sample data. It demonstrates the intended workflows without a live backend."],
        pos: ["Does RNG replace the POS?", "No. The planned model connects to an existing POS. Square is the first intended connector, with CSV as a fallback."],
        approval: ["Can AI publish or post changes itself?", "Not in this concept. Forecasts, rotas, purchase suggestions and content all require an authorised person to approve them."],
        accounting: ["Is the accounting or payroll HMRC recognised?", "No claim of HMRC recognition is made. Formal VAT and payroll functionality would require separate testing and approval before production use."],
        pilot: ["Can a restaurant join a pilot?", "The concept is designed for UK multi-site hospitality teams. A booking link will appear when a pilot conversation is available."],
      },
    },
    final: {
      title: "See how one operating model changes the week.",
      body: "Explore the sample workspace, then book a walkthrough when booking is available.",
    },
    footer: {
      statement: "Restaurant operations, connected.",
      disclaimer: "Interactive concept only. No live business data, financial posting, payroll filing or publishing occurs on this website.",
      back: "Back to top",
    },
  },
  zh: {
    pageTitle: "RNG｜一套連接餐飲營運的系統",
    pageDescription: "互動產品概念，展示預測、人手、庫存、財務、CRM、marketing 和 CMS 如何連接。",
    skip: "跳到主要內容",
    concept: "互動產品概念",
    sample: "示範數據",
    nav: [["產品", "#product"], ["預測", "#forecast"], ["排班", "#workforce"], ["報表", "#reports"], ["營銷", "#marketing"]],
    explore: "開始互動示範",
    book: "預約示範",
    language: "EN",
    hero: {
      title: "一套系統，睇清每間店。",
      body: "將銷售、人手、庫存、財務同營銷連起來，細小 variance 未變成大問題之前已經睇到。",
      imageAlt: "餐廳經理在開放式廚房旁用平板電腦查看營運資料",
    },
    workspace: {
      title: "今日營運一覽",
      selector: "選擇營運範圍",
      revenue: "淨收入",
      forecast: "預測",
      labour: "人工成本",
      gp: "毛利",
      alerts: "庫存提示",
      approvals: "待批核",
      live: "所有數字來自同一個模型",
      varianceAhead: "高過預測",
      belowForecast: "低過預測",
      orders: "今日訂單",
    },
    loop: {
      title: "一個 forecast，帶動成個星期。",
      body: "所有決定都用同一個需求版本，營運同財務毋須再爭論邊一個數字先正確。",
      labels: { forecast: "預測需求", rota: "建立更表", inventory: "安排入貨", reconcile: "財務對數", report: "發佈月報" },
      details: {
        forecast: ["需求有版本記錄", "收入同產品需求一齊更新。"],
        rota: ["人手覆蓋需求", "建議工時控制在人工預算之內。"],
        inventory: ["庫存跟隨需求", "建議訂貨同時計算配方用量同損耗。"],
        reconcile: ["先處理異常", "銷售、結算同銀行入數在月結前對齊。"],
        report: ["一份已批核數字", "月報保留每個來源同 variance 的追溯資料。"],
      },
    },
    platform: {
      title: "每一更背後的營運系統。",
      body: "由現場問題直接睇到決定、負責人同財務影響，毋須轉換工具。",
      items: {
        forecast: ["預測及 variance", "五星期需求規劃，同時比較實際、預算同 forecast。"],
        workforce: ["人手管理", "按需求建立、批核及發佈排班。"],
        inventory: ["庫存", "配方、採購單、盤點、損耗同理論食材成本。"],
        finance: ["財務", "雙重入帳流程、結算配對同月結控制。"],
        crm: ["食客及 B2B CRM", "分開管理食客洞察、商業 pipeline 同項目。"],
        marketing: ["Marketing 及 CMS", "規劃內容、管理批核同分析網上曝光。"],
      },
      open: "開啟模組",
    },
    simulator: {
      title: "在星期開始之前先試一次。",
      body: "調整幾個營運假設，即時睇同一個 scenario 如何影響收入、人手同庫存。",
      period: "預測時段",
      periods: ["未來 7 日", "未來 14 日", "未來 5 星期"],
      promotion: "推廣活動",
      promotions: { none: "沒有", standard: "午市優惠", major: "大型推廣" },
      weather: "天氣",
      weatherOptions: { dry: "乾爽", rain: "下雨", hot: "炎熱" },
      footfall: "預計人流",
      projectedRevenue: "預計收入",
      labourHours: "建議工時",
      stockUnits: "庫存單位",
      variance: "對 baseline variance",
      caveat: "只屬示範模型，並非真實預測或保證結果。",
    },
    rota: {
      title: "一份經理解釋得到的更表。",
      body: "建議先顯示覆蓋同成本，只有獲授權的人批核後才會發佈。",
      statuses: { proposed: "建議中", approved: "已批核", published: "已發佈" },
      demand: "需求覆蓋",
      budget: "人工預算",
      scheduled: "已安排",
      people: "員工更表",
      stateCopy: {
        proposed: "AI 建議已準備好，等待經理審核。",
        approved: "經理已批核，但員工仍未看到更表。",
        published: "已批核更表現已向團隊發佈。",
      },
    },
    reports: {
      title: "月結毋須再追 spreadsheet。",
      body: "用同一份鎖定示範 snapshot 檢視財務、營運同增長。",
      tabs: { pnl: "損益", operations: "營運", growth: "增長" },
      preview: "預覽報告",
      month: "六月管理報告",
      actual: "實際",
      budget: "預算",
      variance: "Variance",
      labels: { netSales: "淨銷售", cogs: "食材成本", grossProfit: "毛利", labour: "人工", operatingContribution: "營運貢獻" },
      operations: [["訂單準確度", "96.4%", "各分店表現穩定"], ["損耗佔收入", "1.8%", "Leeds 在檢視配方後改善"], ["人工佔收入", "24.7%", "高過預算 0.5 個百分點"]],
      growth: [["回訪食客", "41.2%", "高過上一個示範時段"], ["自然搜尋曝光", "+8.6%", "本地頁面帶動升幅"], ["Campaign 收入", "£6,840", "透過 campaign 連結追蹤"]],
      explanation: "收入高過預算，但星期五延長收舖更令人工受壓。調整銷售計劃之前，應先檢視收舖人手覆蓋。",
    },
    marketing: {
      title: "Campaign、內容同網上曝光放在一個畫面。",
      body: "將營運背景變成已批核 campaign、本地 landing page 同一個每月成效故事。",
      campaign: "夏季平日午市",
      objective: "增加星期一至四午市到訪",
      budget: "示範預算",
      audience: "到訪兩次以上的本地食客",
      calendar: "內容日曆",
      website: "Landing page 預覽",
      desktop: "桌面",
      mobile: "手機",
      previewTitle: "配合工作節奏的午餐。",
      previewBody: "一份專注的平日餐牌，在午休開始時已經準備好。",
      previewCta: "查看餐牌",
      checklist: "SEO、GEO 及 AEO readiness",
      checks: ["Restaurant schema", "本地實體資料", "清晰答案摘要", "來源及檢視日期"],
      statuses: { approved: "已批核", draft: "草稿", review: "審核中", planned: "已規劃" },
    },
    roles: {
      title: "總部睇得清，前線用得着。",
      body: "同一個營運模型，會因應作決定的人同執行服務的人顯示不同重點。",
      items: ["總部", "財務", "分店經理", "前線員工"],
      imageAltOne: "深木服務櫃台和綠色天花的餐廳室內",
      imageAltTwo: "設有玻璃入口的獨立餐廳門面",
    },
    faq: {
      title: "示範之前的常見問題。",
      items: {
        concept: ["這是已完成的產品嗎？", "不是。這個網站以本地示範數據展示產品概念同預期流程，沒有連接真正 backend。"],
        pos: ["RNG 會取代 POS 嗎？", "不會。計劃中的模式會連接現有 POS，第一個預定 connector 是 Square，並以 CSV 作 fallback。"],
        approval: ["AI 可以自行發佈或過帳嗎？", "這個概念不會。Forecast、更表、採購建議同內容都需要獲授權的人批核。"],
        accounting: ["會計或 payroll 已獲 HMRC 認證嗎？", "網站沒有作出任何 HMRC 認證聲稱。正式 VAT 同 payroll 功能在 production 使用前需要另外測試及批核。"],
        pilot: ["餐廳可以參加 pilot 嗎？", "概念以英國多店餐飲團隊為目標。當可以安排 pilot 對話時，網站才會顯示預約連結。"],
      },
    },
    final: { title: "睇清一個營運模型如何改變成個星期。", body: "先體驗示範 workspace，預約開放後再安排完整 walkthrough。" },
    footer: {
      statement: "將餐飲營運連起來。",
      disclaimer: "只屬互動概念。本網站不會處理真實業務資料、財務過帳、payroll 申報或內容發佈。",
      back: "返回頁頂",
    },
  },
};
